### PR TITLE
Update deprecated createJSModules call

### PR DESCRIPTION
**Pull request by ugiacoman**
Fix for react-native@0.47.1

Relevant https://github.com/facebook/react-native/releases/tag/v0.47.0

### CODE REVIEW

**Comment by dieseldjango** [comment]
I ran into this issue as well, and also noticed that build.gradle lists react-native 0.20.1 as a dependency. Perhaps this should be changed to '+'.

**Comment by evollu** [comment]
looks good

**Comment by evollu** [comment]
@mCodex can you merge

**Comment by mCodex** [comment]
Hello guys, sorry for delaying the answer. I appreciate your help guys!!

**Pull request closed without merging**
