### PR TITLE
[Windows] vnext c++ app support added

### PR DESCRIPTION
**Pull request by tero-paananen**
Now both Windows vnext C# and C++ applications can use this module (`TargetPlatformMinVersion `change).

And fix for `sharedPreferences()`

**BUT I could not install** this module currently my app using `yarn install`. JS build files were missing? How files should be generated. `MyApp/node_modules/react-native-sensitive-info/` does not contain build folder that is in modules package.json ` "main": "build/index.js",` and files are missing.

### CODE REVIEW

**Comment by tero-paananen** [comment]
Error about missing `node_modules\react-native-sensitive-info\build\index.js`
```
Metro has encountered an error: While trying to resolve module `react-native-sensitive-info` 
from file `C:\Users\tepaa\Developer\HelloCS\App.js`, 
the package `C:\Users\tepaa\Developer\HelloCS\node_modules\react-native-sensitive-info\package.json` was successfully found. 

However, this package itself specifies a `main` module field that could not be resolved 
(`C:\Users\tepaa\Developer\HelloCS\node_modules\react-native-sensitive-info\build\index.js`.
```

How to solve this? :-) Sorry

**Comment by exotexot** [comment]
Hi,

I can reproduce this error, but also have no real clue how to solve it. Only thing I can do is to provide my working version, which somehow managed to generate the build folder. When copying the build folder in this PR, I can run the module just fine.

[react-native-sensitive-info_bak.zip](https://github.com/mCodex/react-native-sensitive-info/files/5174555/react-native-sensitive-info_bak.zip)

**Comment by mCodex** [comment]
First of all thank you for your support!! RNSInfo now is "compiled" using typescript then to generate the build folder you just need to run `yarn build` on RNSInfo root folder 😄

**Review by exotexot — APPROVED** [review]
Looking good to me.
Loweing the TargetPlatformMinVersion is vital to get C# modules running in a shared C++/C# environment and the obsolete GetValueOrDefault was replaced with newer TryGetValue. Well done.

**Comment by tero-paananen** [comment]
> First of all thank you for your support!! RNSInfo uses typescript now then to generate the build folder you just need to run `yarn build` on RNSInfo root folder 😄

Yes, i did noticed that. 

But when referencing to forked package in my app'a package.json ` "react-native-sensitive-info": "git+ssh://git@github.com:showell-labs/react-native-sensitive-info.git#xyz"` build folder still seems to be missing. I have to double check. Does this work so that when developers use "official" package **from  npm** then `build` folder really exists, for example `https://github.com/mCodex/react-native-sensitive-info.git` ?

**Comment by exotexot** [comment]
This may be offtopic, but sounds like a similar issue. I recently made a fork for react-native-static-server to also provide a running version for react-native-windows and I also have problems installing it using package.json. It always install the Upstream repo, even after referencing it correctly like you do. When I'm cloning the repo, it works fine, but installation through package.json isnt working for me somehow.

Maybe I'm just screwing it up, idk..

**Comment by tero-paananen** [comment]
I quess that when @mCodex  does release build into **npm** he builds `react-native-sensitive-info\build\` folder and stores it also into npm.

We that are using our own forgs from the git repo does not have the build folder. I would be nice to find some easy solution to generate it automatically.

**Comment by mCodex** [comment]
`I quess that when @mCodex does release build into npm he builds react-native-sensitive-info\build\ folder and stores it also into npm.`

You're totally right. When I release a new version I generate the build folder and upload it to npm. For reference the screenshot below shows which files are downloaded when you install RNSInfo through npm:

Screen Shot 2020-09-09 at 10 21 57 AM

The `build` folder isn't versioned into git, because it is auto-generated like `node_modules` so this is why it is not available in RNSInfo's git plus this folder isn't "maintainable".

`I would be nice to find some easy solution to generate it automatically.`

Yeah, btw nice idea. I need to find a way to do this.

**Review by mCodex — APPROVED** [review]

**Comment by exotexot** [comment]
This PR is not working with latest RN 0.63 version, as there is a breaking change for C# packages regarding ReactNative.Shared reference

**Comment by tero-paananen** [comment]
> This PR is not working with latest RN 0.63 version, as there is a breaking change for C# packages regarding ReactNative.Shared reference

Yes this works only on rn-windows 0.62.x and someday when i start to use rn-windows 0.63 i will make new PR about that if this is still issue then

**Comment by tero-paananen** [comment]
You could make new issue about that

**Pull request merged**
