### PR TITLE
Windows vNext

### PR DESCRIPTION
**Pull request by tero-paananen**
Windows vNext support. Does not support older react-native-windows versions

"react": "16.13.1",
"react-native": "0.62.2",
"react-native-windows": "0.62.5",

### CODE REVIEW

**Comment by mCodex** [comment]
@tero-paananen many thanks! 😄

**Comment by exotexot** [comment]
Are there any additional steps one need to do to get this running in rnw vnext?
I'm using the latest v6 alpha but recieve a "TypeError: _reactNativeSensitiveInfo.default.setItem is not a function"
while using: https://mcodex.dev/react-native-sensitive-info/docs/#v6x

**Comment by tero-paananen** [comment]
I use my PR code but i try to check also latest v6 tomorrow

**Comment by tero-paananen** [comment]
I started to use latest version from master that was currently `6.0.0-alpha.5`. It seems work in my app.

Maybe you are missing `PackageProviders.Add(new RNSensitiveInfo.ReactPackageProvider());` in your `App.xaml.cs` before `this.InitializeComponent();` ?

**Comment by exotexot** [comment]
Hi Tero, I guess this is the same problem as described here: https://github.com/react-native-community/react-native-device-info/issues/1070 

How to deal with c# modules in a c++ environment?

**Comment by tero-paananen** [comment]
I will make a HelloWorld c++ app and try to use this c# module with it. All help is welcome.

**Comment by exotexot** [comment]
Unfortunately the fix for deviceInfo doesnt apply to senstive info. :/
After following the steps mentioned in the device-info discussion, I'm getting errors after adding RNSenstiveInfo to the solution.

siwin

**Comment by tero-paananen** [comment]
I tried to add C++ application support in PR https://github.com/mCodex/react-native-sensitive-info/pull/235

**Pull request merged**
