### PR TITLE
Add Windows module for react-native-windows

### PR DESCRIPTION
**Pull request by zerglingno1**
Hi @mCodex 
We are working on a React Native project which supports both iOS and Windows.

In our project, we used your module for saving some sensitive infomation
Because your react-native-sensitive-info hasn't supported React Native on Windows yet so we had to created it and we choose Windows.Security.Credentials to implement your libray to windows

Finally, we decided to make it public which could be helpful to people who are looking the solution for React Native Windows.
Please consider to merge it.

Thank you in advance.
Hungdt

Windows Module's credit from @scubism http://s-cubism.jp/

### CODE REVIEW

**Comment by hnq90** [comment]
:+1:

**Comment by mCodex** [comment]
Hello, @zerglingno1. Thank you for your pull request. I'd like to ask you if Windows uses a "key name" to store values Windows.Security.Credentials? (as iOS and Android does) If so, did you use a default key? =)

**Comment by zerglingno1** [comment]
@mCodex . I don't see where the default key is set on Android ? Did you mean "store name" ? (it default "shared_preferences")

**Comment by mCodex** [comment]
@zerglingno1, yes :) I just want to know if Windows.Security.Credentials uses a "store name"?

**Pull request merged**
