### PR TITLE
Add Windows C++ implementation

### PR DESCRIPTION
**Pull request by bzoz**
Add module implementation using C++ WinRT. This implementation supports all react-native-windows since 0.61, and includes autolinking support for react-native-windows>=0.63.

Add test and CI for the Windows implementation.

Separate PR will follow with documentation changes.

### CODE REVIEW

**Comment by bzoz** [comment]
Uhm.. @mCodex ping?

**Comment by exotexot** [comment]
System:
    OS: Windows 10 10.0.19041
    CPU: (8) x64 Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz
    Memory: 7.93 GB / 15.97 GB
  Binaries:
    Node: 12.9.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.4 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.10.2 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK:
      AllowDevelopmentWithoutDevLicense: Enabled
      AllowAllTrustedApps: Enabled
      Versions: 10.0.17763.0, 10.0.18362.0, 10.0.19041.0
  IDEs:
    Android Studio: Not Found
    Visual Studio: 15.9.28307.1274 (Visual Studio Community 2017), 16.7.30611.23 (Visual Studio Community 2019)
  Languages:
    Java: Not Found
    Python: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.11.0 => 16.11.0
    react-native: ^0.62.0-0 => 0.62.2
    react-native-windows: ^0.62.0-0 => 0.62.14
  npmGlobalPackages:
    *react-native*: Not Found

Does not work for me in a fresh project.

sibug

**Comment by bzoz** [comment]
I didn't see that before, let me investigate.

**Comment by exotexot** [comment]
The issue appeared due to the missing build folder.

**Comment by bzoz** [comment]
Gave it a spin: https://github.com/bzoz/test-rnw-si
The commits document the way I've set up a fresh 0.62 RNW app. If you check this repo out, running
```
cd TestSI
yarn
npx react-native run-windows
```
should build and start the app. 

Anyway, worked as expected:
image

**Comment by mCodex** [comment]
Hi guys! Many thanks!! :D Sorry about the delay

**Review by mCodex — APPROVED** [review]

**Comment by bzoz** [comment]
@mCodex thanks for merging! There is also the accompanying doc change PR out there: #240

**Comment by mCodex** [comment]
Yeah, I'll merge it after the new release :D

**Pull request merged**
